/**
 * Rejects commit messages that carry third-party AI agent attribution.
 *
 * Called by .husky/commit-msg:
 *   tsx scripts/verify-ai-attribution.ts <commit-msg-file>
 *
 * See docs/git-commit.md. Patterns stay anchored to attribution phrasing so that
 * messages merely mentioning a tool by name -- e.g. "fix: handle claude code MCP timeout" --
 * are not flagged.
 */
import { readFileSync } from "node:fs";

const AI_AGENT_NAMES = ["claude", "copilot", "cursor", "chatgpt"];

const AI_AGENT = `(?:${AI_AGENT_NAMES.join("|")})`;

// 1. Trailer form: "Co-Authored-By: Claude <noreply@anthropic.com>"
// 2. Prose form:   "Generated with Claude Code", "Generated by Copilot", "Generated using [Cursor]"
const ATTRIBUTION_PATTERNS = [
  new RegExp(`^Co-Authored-By:.*\\b${AI_AGENT}\\b`, "im"),
  new RegExp(`\\bGenerated\\s+(?:with|by|using)\\s+\\[?${AI_AGENT}\\b`, "i"),
];

const messageFile = process.argv[2];

if (!messageFile) {
  console.error("Usage: tsx scripts/verify-ai-attribution.ts <commit-msg-file>");
  process.exit(1);
}

const offenders = readFileSync(messageFile, "utf8")
  .split("\n")
  .flatMap((line, index) =>
    ATTRIBUTION_PATTERNS.some((pattern) => pattern.test(line)) ? [`${index + 1}: ${line}`] : [],
  );

if (offenders.length > 0) {
  console.error("");
  console.error("[ERROR] Commit message contains a third-party AI agent attribution.");
  console.error(offenders.join("\n"));
  console.error("");
  console.error("[WARNING] Remove the lines above and retry.");
  process.exit(1);
}
