import { mkdtempSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { findAttributionOffenders, parseArgs, runCli, USAGE } from "./verify-ai-attribution";

/** Collects what the CLI prints instead of letting it pollute the test reporter. */
function captureConsole(): { stdout: string[]; stderr: string[] } {
  const stdout: string[] = [];
  const stderr: string[] = [];

  vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    stdout.push(args.join(" "));
  });
  vi.spyOn(console, "error").mockImplementation((...args: unknown[]) => {
    stderr.push(args.join(" "));
  });

  return { stdout, stderr };
}

let workDir: string;

beforeAll(() => {
  workDir = mkdtempSync(join(tmpdir(), "verify-ai-attribution-"));
});

afterAll(async () => {
  await rm(workDir, { recursive: true, force: true });
});

afterEach(() => {
  vi.restoreAllMocks();
});

/** Writes `content` to a scratch file and returns its path. */
function writeMessageFile(name: string, content: string): string {
  const file = join(workDir, name);
  writeFileSync(file, content, "utf8");
  return file;
}

describe("findAttributionOffenders", () => {
  describe("flags attribution", () => {
    it.each([
      ["trailer", "Co-Authored-By: Claude <noreply@anthropic.com>"],
      ["lowercase trailer", "co-authored-by: claude <noreply@anthropic.com>"],
      ["copilot trailer", "Co-Authored-By: Copilot <noreply@github.com>"],
      ["trailer with extra text", "Co-Authored-By: Claude Code <noreply@anthropic.com>"],
      ["prose with", "Generated with Claude Code"],
      ["prose by", "Generated by Copilot"],
      ["prose using", "Generated using Cursor"],
      ["bracketed tool name", "Generated with [Cursor]"],
      ["lowercase prose", "generated with chatgpt"],
      ["prose mid-sentence", "This change was generated by Claude."],
    ])("flags the %s form: %s", (_label, line) => {
      const offenders = findAttributionOffenders(line);

      expect(offenders).toEqual([`1: ${line}`]);
    });

    it("flags offenders inside a full commit message", () => {
      const message = [
        "feat: add login flow",
        "",
        "Generated with Claude Code",
        "Co-Authored-By: Claude <noreply@anthropic.com>",
      ].join("\n");

      expect(findAttributionOffenders(message)).toEqual([
        "3: Generated with Claude Code",
        "4: Co-Authored-By: Claude <noreply@anthropic.com>",
      ]);
    });

    it("reports the 1-based line number of every offending line", () => {
      const message = [
        "chore: bump deps",
        "",
        "Generated by Copilot",
        "",
        "Generated using Cursor",
      ].join("\n");

      expect(findAttributionOffenders(message)).toEqual([
        "3: Generated by Copilot",
        "5: Generated using Cursor",
      ]);
    });

    it("does not carry regex state between calls", () => {
      const message = "Generated with Claude Code";

      expect(findAttributionOffenders(message)).toHaveLength(1);
      expect(findAttributionOffenders(message)).toHaveLength(1);
    });
  });

  describe("leaves technical mentions alone", () => {
    it.each([
      ["plain subject", "feat: add login flow"],
      ["tool name as context", "fix: handle claude code MCP timeout"],
      ["tool name in prose", "this hung on the MCP timeout bug in Claude Code"],
      ["human co-author", "Co-Authored-By: Jane Doe <jane@example.com>"],
      ["tool named in a docs change", "docs: mention copilot in the onboarding guide"],
      ["cursor as a UI concept", "fix: keep the caret aligned with the cursor"],
      ["generated without a tool", "refactor: generated by the build script"],
      ["generated with care", "chore: generated with care"],
      ["empty message", ""],
      ["blank lines only", "\n\n"],
      ["tool name glued to a word", "fix: claudecode MCP timeout"],
    ])("does not flag %s: %s", (_label, line) => {
      expect(findAttributionOffenders(line)).toEqual([]);
    });
  });
});

describe("parseArgs", () => {
  it("treats a lone positional argument as a message file", () => {
    expect(parseArgs(["COMMIT_EDITMSG"])).toEqual({ kind: "file", file: "COMMIT_EDITMSG" });
  });

  it("takes the text after --text", () => {
    expect(parseArgs(["--text", "feat: add login flow"])).toEqual({
      kind: "text",
      text: "feat: add login flow",
    });
  });

  it("accepts an empty --text value", () => {
    expect(parseArgs(["--text", ""])).toEqual({ kind: "text", text: "" });
  });

  it.each([["--help"], ["-h"]])("recognises %s", (flag) => {
    expect(parseArgs([flag])).toEqual({ kind: "help" });
  });

  it("lets --help win over other arguments", () => {
    expect(parseArgs(["COMMIT_EDITMSG", "--help"])).toEqual({ kind: "help" });
  });

  it("rejects --text without a value", () => {
    expect(parseArgs(["--text"])).toEqual({
      kind: "error",
      message: "[ERROR] --text requires a value.",
    });
  });

  it("rejects no argument at all", () => {
    expect(parseArgs([])).toEqual({
      kind: "error",
      message: "[ERROR] No commit message given.",
    });
  });

  it("rejects passing a file and --text together", () => {
    expect(parseArgs(["--text", "feat: add login flow", "COMMIT_EDITMSG"])).toEqual({
      kind: "error",
      message: "[ERROR] Pass either a commit-msg file or --text, not both.",
    });
  });
});

describe("runCli", () => {
  it("returns 0 and stays quiet for a clean message", () => {
    const { stdout, stderr } = captureConsole();

    expect(runCli(["--text", "feat: add login flow"])).toBe(0);
    expect(stdout).toEqual([]);
    expect(stderr).toEqual([]);
  });

  it("returns 1 and lists the offending lines with their numbers", () => {
    const { stderr } = captureConsole();
    const message = "feat: add login flow\n\nGenerated with Claude Code";

    expect(runCli(["--text", message])).toBe(1);
    expect(stderr.join("\n")).toContain("3: Generated with Claude Code");
    expect(stderr.join("\n")).toContain("[WARNING] Remove the lines above and retry.");
  });

  it("reads the message file when given a path", () => {
    const file = writeMessageFile("from-file.txt", "chore: bump deps\n\nGenerated by Copilot\n");
    captureConsole();

    expect(runCli([file])).toBe(1);
  });

  it("returns 0 for a clean message file", () => {
    const file = writeMessageFile("clean.txt", "chore: bump deps\n");
    const { stderr } = captureConsole();

    expect(runCli([file])).toBe(0);
    expect(stderr).toEqual([]);
  });

  it("returns 1 and explains itself when the message file cannot be read", () => {
    const missing = join(workDir, "does-not-exist.txt");
    const { stderr } = captureConsole();

    expect(runCli([missing])).toBe(1);
    expect(stderr.join("\n")).toContain(`[ERROR] Cannot read commit message file (${missing}):`);
  });

  it("prints the usage and returns 0 for --help", () => {
    const { stdout } = captureConsole();

    expect(runCli(["--help"])).toBe(0);
    expect(stdout).toEqual([USAGE]);
  });

  it("prints the usage and returns 1 for bad arguments", () => {
    const { stderr } = captureConsole();

    expect(runCli([])).toBe(1);
    expect(stderr.join("\n")).toContain("[ERROR] No commit message given.");
    expect(stderr.join("\n")).toContain(USAGE);
  });
});

describe("CLI entry guard", () => {
  it("does not run or exit the process when the module is imported", async () => {
    const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
    const { stdout, stderr } = captureConsole();

    vi.resetModules();
    await import("./verify-ai-attribution");

    expect(exit).not.toHaveBeenCalled();
    expect(stdout).toEqual([]);
    expect(stderr).toEqual([]);
  });
});
