
name: build website

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    steps:
      - name: Copy Codes
        uses: actions/checkout@v4

      - name: setup node@24.21.0
        uses: actions/setup-node@v4
        with:
          node-version: "24.21.0"

      - name: Install pnpm@11.26.0
        uses: pnpm/action-setup@v4
        with:
          version: 11.26.0

      - name: Install Dependencies.
        run: pnpm install

      - name: Build Dist.
        run: pnpm build:github-page

      - name: Setup GitHub Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy GitHub Pages
        if: github.event_name != 'pull_request'
        id: pages
        uses: actions/deploy-pages@v4

      - name: Deploy To My Remote Server [Aliyun]
        if: github.event_name != 'pull_request'
        uses: easingthemes/ssh-deploy@v5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY_ALIYUN }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_ALIYUN }}
          REMOTE_USER: "root"
          TARGET: "/var/www/big-screen"
          ARGS: "-avzr --delete"
          SOURCE: "./dist/"
          EXCLUDE: "/node_modules/"

      - name: Deploy To My Remote Server [Japanese]
        if: github.event_name != 'pull_request'
        uses: easingthemes/ssh-deploy@v5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY_JP }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_JP }}
          REMOTE_USER: "root"
          TARGET: "/var/www/big-screen"
          ARGS: "-avzr --delete"
          SOURCE: "./dist/"
          EXCLUDE: "/node_modules/"
