name: build website

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Codes
        uses: actions/checkout@v4

      - name: setup node@16.20.1
        uses: actions/setup-node@v4
        with:
          node-version: "16.20.1"

      - name: Install pnpm@7.30.5
        uses: pnpm/action-setup@v4
        with:
          version: 7.30.5

      - name: Install Dependencies.
        run: pnpm install

      - name: Build Dist.
        run: pnpm build:github-page

      - name: Deploy To GitHub Page.🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-page
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy To My Remote Server [Aliyun]
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY_ALIYUN }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_ALIYUN }}
          REMOTE_USER: "root"
          TARGET: "/var/www/big-screen"
          ARGS: "-avzr --delete"
          SOURCE: "./dist/"
          EXCLUDE: "/node_modules/"

      - name: Deploy To My Remote Server [Japanese]
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY_JP }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_JP }}
          REMOTE_USER: "root"
          TARGET: "/var/www/big-screen"
          ARGS: "-avzr --delete"
          SOURCE: "./dist/"
          EXCLUDE: "/node_modules/"
